BOT_NAME = 'scraper'
SPIDER_MODULES = ['scraper.spiders']
NEWSPIDER_MODULE = 'scraper.spiders'

LOG_LEVEL = 'INFO'
TELNETCONSOLE_ENABLED = False
ROBOTSTXT_OBEY= False
FEED_EXPORT_ENCODING = 'utf-8'

DOWNLOAD_TIMEOUT= 15
RETRY_TIMES= 2
CONCURRENT_REQUESTS= 8

COOKIES_ENABLED = True

